### ISSUE TITLE
后台管理重置客户端秘钥后不会立即生效

### ISSUE THREAD

**Issue by AzXuan** [zero-rp/ops#11]
![image](https://github.com/user-attachments/assets/98db0e4c-43bf-4bdb-b81b-8fb3b46bc7af)
![image](https://github.com/user-attachments/assets/7fb7b001-e6df-47d7-9d4d-c92d481766a8)

如图，重置秘钥后，需要重启服务端后秘钥才能生效

**Comment by zero-rp** [comment]
已修复
