### ISSUE TITLE
请问应该怎么使用组网功能？

### ISSUE THREAD

**Issue by litangde** [zero-rp/ops#15]
请问应该怎么使用组网功能？

**Comment by zero-rp** [comment]
在VPC页面添加网段,不同网段之间是隔离的
![1](https://github.com/user-attachments/assets/fe27f7f1-97cf-44dd-accc-fd06af33be53)
然后在VPC成员页面指定每个客户端的内网IP就可以了
![2](https://github.com/user-attachments/assets/189caf42-43ca-4462-880a-1908086a171a)
这样在同网段下的客户端之间就可以直接通过对方设置的ip访问

**Comment by litangde** [comment]
非常感谢回复。
我服务器端和客户端都是win。
现在的问题是我服务器端运行了，然后客户端也用对应的命令连上了，但是web管理里面始终看不到在线。一直显示离线。
![image](https://github.com/user-attachments/assets/14f73443-00ba-4def-944e-47c60c9dc714)
<img width="200" alt="image" src="https://github.com/user-attachments/assets/c3c40aef-ad98-4ca0-b397-0618acfb04ce">
服务器段也显示 new client 了，但是web上查看就是离线

**Comment by zero-rp** [comment]
这个release版本显示在线有问题,不影响使用

**Comment by litangde** [comment]
按您的步骤设置了，还是ping不通，还需要设置什么吗？

**Comment by zero-rp** [comment]
重启下客户端看看有没有创建虚拟网卡

**Comment by litangde** [comment]
重启了，没有创建虚拟网卡。我用管理员权限打开C客户端，还是没创建。该如何创建虚拟网卡？

**Comment by zero-rp** [comment]
客户端目录下有wintun.dll这个库吗,配置截图看看呢

**Comment by litangde** [comment]
![image](https://github.com/user-attachments/assets/5b3fdab5-e6cd-4892-92a8-b35dbba6ec0e)
![image](https://github.com/user-attachments/assets/4f9640f2-3cfc-48e7-a70a-7b658fde2cbb)
<img width="879" alt="image" src="https://github.com/user-attachments/assets/2fdfb860-5d22-459e-8d35-7c86179ff9dd">
<img width="911" alt="image" src="https://github.com/user-attachments/assets/fad6dd31-6dae-43b7-943a-9644c187f979">
<img width="896" alt="image" src="https://github.com/user-attachments/assets/914c1c8a-efd6-40f8-88b6-75fd2e3069ed">

**Comment by litangde** [comment]
这个没问题，非常感谢，好人一生平安

**Comment by zero-rp** [comment]
那就行,你先用着,等我发下个版本在换

**Comment by litangde** [comment]
如果可以的话，能为 主机 和 转发 这两个功能写一个类似的示例吗？刚接触这个，请多指教，非常感谢，好人一生平安
