### ISSUE TITLE
ops 启动后  js css  文件  感觉无法加载。 

### ISSUE THREAD

**Issue by xjdata** [zero-rp/ops#2]
![image](https://github.com/zero-rp/ops/assets/4524983/e4edfe15-17ad-45c5-b905-7746eee5099b)

![image](https://github.com/zero-rp/ops/assets/4524983/946dbb00-6644-404c-88c3-b6a43fd5ad16)

![image](https://github.com/zero-rp/ops/assets/4524983/0c5e69f9-ccbb-4845-bd0f-0c01245660c3)

![image](https://github.com/zero-rp/ops/assets/4524983/61551cbf-b285-4d8a-844d-bddf06cdef58)

**Comment by zero-rp** [comment]
请问是用的二进制文件还是代码编译的

**Comment by zero-rp** [comment]
刚才发了个新版本二进制文件,可以试试
