### ISSUE TITLE
请问ops在nps的基础上增加了哪些功能

### ISSUE THREAD

**Issue by sunlewuyou** [zero-rp/ops#3]

**Comment by zero-rp** [comment]
目前主要添加了两个,添加了异地组网,本地转发两个功能,异地组网是通过虚拟网卡实现的,本地转发就是把监听端口暴露在本地机器上,而不在服务器上提供服务,比如有个HTTP服务,你不想暴露到公网,就可以通过本地转发只在你的开发主机上监听端口,你访问本地端口就能访问到远程服务,安全性更加提高

**Comment by zero-rp** [comment]
也是跨平台的,编译脚本是cmake,目前在linux,win,android都能编译通过

**Comment by dossec** [comment]
有后台管理界面吗？这个和frp有啥区别呢

**Comment by zero-rp** [comment]
有web管理页面
