### ISSUE TITLE
无法连接服务端，报Connection refused，在服务器运行客户端就可连接上。

### ISSUE THREAD

**Issue by wangeDear** [zero-rp/ops#4]
![image](https://github.com/zero-rp/ops/assets/9948504/6b612128-9ceb-4736-871d-ddef309633cb)

**Comment by zero-rp** [comment]
请问你的启动参数是什么

**Comment by wangeDear** [comment]
> 请问你的启动参数是什么

./opc -h x.x.x.x:8025 -a c07935ad6d4a9b886736987439274512

x.x.x.x为远程服务端ip

服务端启动：
./ops

**Comment by wangeDear** [comment]
![image](https://github.com/zero-rp/ops/assets/9948504/a6599906-68e1-4a02-bdb6-3d98c5163751)
有启动8025端口，客户端telnet也是通的
![image](https://github.com/zero-rp/ops/assets/9948504/e6201943-c1d2-4031-b1e8-68323f7e0188)

**Comment by zero-rp** [comment]
-h: 服务端ip,默认127.0.0.1
-p: 服务器端口,默认8025
ip和端口是独立参数
